const td=new TextDecoder();
const SUPPORTED_ROUTES=['40','特40','直行40','臨時'];

function readVarint(bytes,start){let value=0n,shift=0n,pos=start;for(;pos<bytes.length&&shift<70n;pos++){const b=BigInt(bytes[pos]);value|=(b&127n)<<shift;if((b&128n)===0n)return {value,pos:pos+1};shift+=7n;}throw Error('GTFS-RT protobufが壊れています。');}
function readFloat(bytes,pos){if(pos+4>bytes.length)throw Error('GTFS-RT floatが壊れています。');return new DataView(bytes.buffer,bytes.byteOffset+pos,4).getFloat32(0,true);}
function fieldIterator(bytes){let pos=0;return {next(){if(pos>=bytes.length)return {done:true};const tag=readVarint(bytes,pos);pos=tag.pos;const no=Number(tag.value>>3n),wire=Number(tag.value&7n),start=pos;let value,end;if(wire===0){const v=readVarint(bytes,pos);value=v.value;pos=v.pos;end=pos;}else if(wire===1){pos+=8;end=pos;value=bytes.subarray(start,pos);}else if(wire===2){const n=readVarint(bytes,pos);pos=n.pos;const len=Number(n.value);value=bytes.subarray(pos,pos+len);pos+=len;end=pos;}else if(wire===5){pos+=4;end=pos;value=bytes.subarray(start,pos);}else throw Error(`未対応のprotobuf wire type: ${wire}`);if(pos>bytes.length)throw Error('GTFS-RT protobufが途中で切れています。');return {done:false,value:{no,wire,value,start,end}};},[Symbol.iterator](){return this;}};}
const str=b=>td.decode(b);
const signed32=v=>Number(BigInt.asIntN(32,v));

function tripDescriptor(bytes){const out={trip:null,route:null,direction:null};for(const f of fieldIterator(bytes)){if(f.no===1&&f.wire===2)out.trip=str(f.value);else if(f.no===5&&f.wire===2)out.route=str(f.value);else if(f.no===6&&f.wire===0)out.direction=Number(f.value);}return out;}
function vehicleDescriptor(bytes){const out={id:null,label:null};for(const f of fieldIterator(bytes)){if(f.no===1&&f.wire===2)out.id=str(f.value);else if(f.no===2&&f.wire===2)out.label=str(f.value);}return out;}
function position(bytes){const out={lat:null,lon:null,bearing:null,speed:null};for(const f of fieldIterator(bytes)){if(f.wire!==5)continue;const v=readFloat(f.value,0);if(f.no===1)out.lat=v;else if(f.no===2)out.lon=v;else if(f.no===3)out.bearing=v;else if(f.no===5)out.speed=v;}return out;}
function vehiclePosition(bytes){const out={trip:null,route:null,direction:null,id:null,label:null,lat:null,lon:null,bearing:null,speed:null,timestamp:null,stop:null,stopSequence:null,status:null,congestion:null,occupancy:null,occupancyPct:null};for(const f of fieldIterator(bytes)){if(f.no===1&&f.wire===2)Object.assign(out,tripDescriptor(f.value));else if(f.no===2&&f.wire===2)Object.assign(out,position(f.value));else if(f.no===3&&f.wire===0)out.stopSequence=Number(f.value);else if(f.no===4&&f.wire===0)out.status=Number(f.value);else if(f.no===5&&f.wire===0)out.timestamp=Number(f.value);else if(f.no===6&&f.wire===0)out.congestion=Number(f.value);else if(f.no===7&&f.wire===2)out.stop=str(f.value);else if(f.no===8&&f.wire===2)Object.assign(out,vehicleDescriptor(f.value));else if(f.no===9&&f.wire===0)out.occupancy=Number(f.value);else if(f.no===10&&f.wire===0)out.occupancyPct=Number(f.value);}return out;}
function stopTimeEvent(bytes){for(const f of fieldIterator(bytes))if(f.no===1&&f.wire===0)return signed32(f.value);return null;}
function stopTimeUpdate(bytes){let seq=null,delay=null;for(const f of fieldIterator(bytes)){if(f.no===1&&f.wire===0)seq=Number(f.value);else if((f.no===2||f.no===3)&&f.wire===2){const d=stopTimeEvent(f.value);if(Number.isFinite(d))delay=d;}}return {seq,delay};}
function tripUpdate(bytes){const out={trip:null,route:null,direction:null,timestamp:null,delay:null,stops:[]};for(const f of fieldIterator(bytes)){if(f.no===1&&f.wire===2)Object.assign(out,tripDescriptor(f.value));else if(f.no===2&&f.wire===2)out.stops.push(stopTimeUpdate(f.value));else if(f.no===4&&f.wire===0)out.timestamp=Number(f.value);else if(f.no===5&&f.wire===0)out.delay=signed32(f.value);}return out;}
function entity(bytes){let vehicle=null,update=null;for(const f of fieldIterator(bytes)){if(f.no===3&&f.wire===2)update=tripUpdate(f.value);else if(f.no===4&&f.wire===2)vehicle=vehiclePosition(f.value);}return {vehicle,update};}
export function decodeGtfsRealtime(input){const bytes=input instanceof Uint8Array?input:new Uint8Array(input),vehicles=[],tripUpdates=[];for(const f of fieldIterator(bytes)){if(f.no!==2||f.wire!==2)continue;const e=entity(f.value);if(e.vehicle)vehicles.push(e.vehicle);if(e.update)tripUpdates.push(e.update);}return {vehicles,tripUpdates};}
export function routeLabel(routeId){const s=String(routeId??'').normalize('NFKC').replace(/\s+/g,'');if(!s)return null;for(const label of ['直行40','特40','臨時','40']){const escaped=label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');if(new RegExp(`(?:^|[._:/-])${escaped}(?:$|[._:/-])`).test(s)||s===label)return label;}return null;}
export function filterKyotoBusVehicles(vehicles,updates=[],nowSec=Math.floor(Date.now()/1000)){const byTrip=new Map(updates.filter(u=>u.trip).map(u=>[u.trip,u]));let unmapped=0;const rows=[];for(const v of vehicles){const route=routeLabel(v.route);if(!route||!SUPPORTED_ROUTES.includes(route)){unmapped++;continue;}const u=byTrip.get(v.trip);let delaySec=Number.isFinite(u?.delay)?u.delay:null;if(delaySec===null&&u?.stops?.length){const candidates=u.stops.filter(s=>Number.isFinite(s.delay)&&Number.isFinite(s.seq));const current=Number.isFinite(v.stopSequence)?v.stopSequence:null;const best=current===null?candidates[0]:candidates.sort((a,b)=>Math.abs(a.seq-current)-Math.abs(b.seq-current))[0];delaySec=best?.delay??null;}rows.push({id:v.id??v.label??v.trip,trip:v.trip,route,lat:v.lat,lon:v.lon,bearing:v.bearing,speed:v.speed,timestamp:v.timestamp,stop:v.stop,stopSequence:v.stopSequence,congestion:v.congestion,occupancy:v.occupancy,occupancyPct:v.occupancyPct,delay:Number.isFinite(delaySec)?Math.round(delaySec/60):null,fresh:Number.isFinite(v.timestamp)&&nowSec-v.timestamp<=90});}return {vehicles:rows,unmapped};}
export function decayDelay(delay,followingTrips=0){if(!Number.isFinite(delay))return null;return delay*(.5**Math.max(0,followingTrips));}
export function freshMeasurement(timestamp,nowSec=Math.floor(Date.now()/1000),limit=90){return Number.isFinite(timestamp)&&timestamp<=nowSec+5&&nowSec-timestamp<=limit;}
